=== Aviater/user_acceptance_tests/server/xml/system_order_stock/system_order_stock.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SystemOrderStock (Given,When,Then)>
<!ELEMENT Given (ItemsToOrder)>
<!ELEMENT ItemsToOrder (Item+)>
<!ELEMENT Item (Id, Quantity)>
<!ELEMENT When (Order)>
<!ATTLIST Order sent (true|false) #REQUIRED>
<!ELEMENT Then (Reply)>
<!ATTLIST Reply received (true|false) #REQUIRED>

<!ELEMENT Id (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT Order (#PCDATA)>
<!ELEMENT Reply (#PCDATA)>

=== Aviater/user_acceptance_tests/server/xml/system_order_stock/system_order_stock.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemOrderStock SYSTEM "system_order_stock.dtd">
<SystemOrderStock>
	<Given>
		<ItemsToOrder>
			<Item>
				<Id>20A</Id>
				<Quantity>2</Quantity>
			</Item>
			<Item>
				<Id>22C</Id>
				<Quantity>1</Quantity>
			</Item>
		</ItemsToOrder>
	</Given>
	<When>
		<Order sent="true"></Order>
	</When>
	<Then>
		<Reply received="true">Order placed</Reply>
	</Then>
</SystemOrderStock>
