=== Aviater/user_acceptance_tests/server/xml/system_message/system_message.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SystemMessage (Given,When,Then)>
<!ELEMENT Given (ItemsToSend)>
<!ELEMENT ItemsToSend (Item+)>
<!ELEMENT Item (Id, Quantity)>
<!ELEMENT When (Message)>
<!ATTLIST Message sent (true|false) #REQUIRED>
<!ELEMENT Then (Reply)>
<!ATTLIST Reply received (true|false) #REQUIRED>

<!ELEMENT Id (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT Message (#PCDATA)>
<!ELEMENT Reply (#PCDATA)>

=== Aviater/user_acceptance_tests/server/xml/system_message/system_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemMessage SYSTEM "system_message.dtd">
<SystemMessage>
	<Given>
		<ItemsToSend>
			<Item>
				<Id>20A</Id>
				<Quantity>2</Quantity>
			</Item>
			<Item>
				<Id>22C</Id>
				<Quantity>1</Quantity>
			</Item>
		</ItemsToSend>
	</Given>
	<When>
		<Message sent="true"></Message>
	</When>
	<Then>
		<Reply received="true"></Reply>
	</Then>
</SystemMessage>
