=== Aviater/user_acceptance_tests/server/xml/system_query_stock/system_query_stock.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SystemQueryStock (Given,When,Then)>
<!ELEMENT Given (ItemToQuery)>
<!ELEMENT ItemToQuery (Id)>
<!ELEMENT When (Message)>
<!ATTLIST Message sent (true|false) #REQUIRED>
<!ELEMENT Then (Reply)>
<!ELEMENT Reply (QueriedItem)>
<!ELEMENT QueriedItem (Id, Stock)>

<!ELEMENT Id (#PCDATA)>
<!ELEMENT Message (#PCDATA)>
<!ELEMENT Stock (#PCDATA)>

=== Aviater/user_acceptance_tests/server/xml/system_query_stock/system_query_stock.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemQueryStock SYSTEM "system_query_stock.dtd">
<SystemQueryStock>
	<Given>
		<ItemToQuery>
			<Id>20A</Id>
		</ItemToQuery>
	</Given>
	<When>
		<Message sent="true"></Message>
	</When>
	<Then>
		<Reply>
			<QueriedItem>
				<Id>20A</Id>
				<Stock>42</Stock>
			</QueriedItem>
		</Reply>
	</Then>
</SystemQueryStock>
